export const LEADERSHIP_FEED = {
  showBackgroundStar: true,
  widgetKey: "leadership-updates",
  apiBase: "/leadership-updates",
  cardTitle: "Leadership Updates",
  pageTitle: "Leadership Updates",
  archiveSubtitle: "Past updates",
  archivePastLabel: "Past updates",
  detailSubtitleFallback: "Update",
  emptyCardMessage: "No leadership updates have been published yet.",
  emptyArchiveMessage: "No leadership updates have been published yet.",
  adminPath: "/admin/leadership-updates",
  archivePath: "/leadership-updates",
  adminAddLinkLabel: "Add an update",
  adminSaveNewLabel: "Add leadership update",
  adminSaveEditLabel: "Update entry",
  adminIntro:
    "Add leadership messages for the home page. Use the sort arrows so the entry you want featured appears first among published items.",
  titleFieldLabel: "Title",
  titlePlaceholder: "Update headline…",
  messageFieldLabel: "Message",
  messagePlaceholder: "Leadership message or summary…",
  linkFieldLabel: "Link (optional)",
  imageFieldLabel: "Image (optional)",
  publishLabel: "Published on home page",
  tableDateHeader: "Date",
  tableTitleHeader: "Title",
};

export const NEW_HIRES_FEED = {
  showBackgroundStar: false,
  widgetKey: "new-hires",
  apiBase: "/new-hires",
  cardTitle: "New Hires",
  pageTitle: "New Hires",
  archiveSubtitle: "Past hires",
  archivePastLabel: "Past hires",
  detailSubtitleFallback: "New hire",
  emptyCardMessage: "No new hires have been published yet.",
  emptyArchiveMessage: "No new hires have been published yet.",
  adminPath: "/admin/new-hires",
  archivePath: "/new-hires",
  adminAddLinkLabel: "Add a new hire",
  adminSaveNewLabel: "Add new hire",
  adminSaveEditLabel: "Update entry",
  adminIntro:
    "Welcome new team members on the home page. Use the sort arrows so the new hire you want featured appears first among published items.",
  titleFieldLabel: "Name",
  titlePlaceholder: "New hire name…",
  messageFieldLabel: "Welcome message",
  messagePlaceholder: "Role, department, or welcome note…",
  linkFieldLabel: "Link (optional)",
  imageFieldLabel: "Photo (optional)",
  publishLabel: "Published on home page",
  tableDateHeader: "Date",
  tableTitleHeader: "Name",
};

export const CUSTOMER_WINS_FEED = {
  showBackgroundStar: false,
  widgetKey: "customer-wins",
  apiBase: "/customer-wins",
  cardTitle: "Customer Wins",
  pageTitle: "Customer Wins",
  archiveSubtitle: "Past wins",
  archivePastLabel: "Past wins",
  detailSubtitleFallback: "Customer win",
  emptyCardMessage: "No customer wins have been published yet.",
  emptyArchiveMessage: "No customer wins have been published yet.",
  adminPath: "/admin/customer-wins",
  archivePath: "/customer-wins",
  adminAddLinkLabel: "Add a customer win",
  adminSaveNewLabel: "Add customer win",
  adminSaveEditLabel: "Update entry",
  adminIntro:
    "Highlight customer wins on the home page. Use the sort arrows so the win you want featured appears first among published items.",
  titleFieldLabel: "Title",
  titlePlaceholder: "Customer or project name…",
  messageFieldLabel: "Summary",
  messagePlaceholder: "What we delivered or achieved…",
  linkFieldLabel: "Link (optional)",
  imageFieldLabel: "Image (optional)",
  publishLabel: "Published on home page",
  tableDateHeader: "Date",
  tableTitleHeader: "Title",
};

export const COMMUNITY_INVOLVEMENT_FEED = {
  showBackgroundStar: false,
  widgetKey: "community-involvement",
  apiBase: "/community-involvement",
  cardTitle: "Community Involvement",
  pageTitle: "Community Involvement",
  archiveSubtitle: "Past highlights",
  archivePastLabel: "Past highlights",
  detailSubtitleFallback: "Community involvement",
  emptyCardMessage: "No community involvement highlights have been published yet.",
  emptyArchiveMessage: "No community involvement highlights have been published yet.",
  adminPath: "/admin/community-involvement",
  archivePath: "/community-involvement",
  adminAddLinkLabel: "Add a highlight",
  adminSaveNewLabel: "Add community highlight",
  adminSaveEditLabel: "Update entry",
  adminIntro:
    "Share community involvement stories on the home page. Use the sort arrows so the highlight you want featured appears first among published items.",
  titleFieldLabel: "Title",
  titlePlaceholder: "Event or initiative name…",
  messageFieldLabel: "Summary",
  messagePlaceholder: "How we contributed or participated…",
  linkFieldLabel: "Link (optional)",
  imageFieldLabel: "Image (optional)",
  publishLabel: "Published on home page",
  tableDateHeader: "Date",
  tableTitleHeader: "Title",
};

export const BOTTOM_ROW_FEEDS = [NEW_HIRES_FEED, CUSTOMER_WINS_FEED, COMMUNITY_INVOLVEMENT_FEED];
